### PR TITLE
Finalise developer guide

### LINKED ISSUE #297: Update developer guide
Finalise all details and diagrams in the developer guide for the v1.4 submission.

### PR DESCRIPTION
**Pull request by zhaojj2209**
Resolves #297.

### CODE REVIEW

**Review by yongping827 — DISMISSED** [review]
LGTM

**Review by wltan — APPROVED** [review]
LGTM!

**Review by wltan — CHANGES_REQUESTED** [review]
Remove references to Find expense/income as there is no such use case anymore

image

**Review by siddarth2824 — APPROVED** [review]
LGTM!

**Review by wltan — APPROVED** [review]
LGTM!

**Pull request merged**
